# Generated by Django 4.1.6 on 2023-03-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='UpFile',
        ),
    ]
